import { inflateRawSync } from "node:zlib";
const TSE = "https://divulgacandcontas.tse.jus.br/divulga/rest/v1";
const CKAN = "https://dadosabertos.tse.jus.br/api/3/action/package_show?id=eleitorado-2026";
export const ELECTION_ID = "20322002026";
const cache = new Map(), ttl = 10 * 60 * 1000;
async function cached(key, loader) { const hit=cache.get(key); if(hit && Date.now()-hit.at<ttl) return hit.value; const value=await loader(); cache.set(key,{at:Date.now(),value}); return value; }
async function fetchJson(url) { const r=await fetch(url,{headers:{"User-Agent":"Civica-MA/2.0","Accept":"application/json"}}); if(!r.ok) throw new Error(`Fonte respondeu ${r.status}`); return r.json(); }
function extractFirstCsv(zipBuffer) { const b=Buffer.from(zipBuffer), sig=0x06054b50; let e=-1; for(let i=b.length-22;i>=Math.max(0,b.length-65557);i--){if(b.readUInt32LE(i)===sig){e=i;break}} if(e<0)throw new Error("ZIP inválido"); const count=b.readUInt16LE(e+10); let p=b.readUInt32LE(e+16); for(let n=0;n<count;n++){if(b.readUInt32LE(p)!==0x02014b50)break; const method=b.readUInt16LE(p+10),size=b.readUInt32LE(p+20),nl=b.readUInt16LE(p+28),el=b.readUInt16LE(p+30),cl=b.readUInt16LE(p+32),lo=b.readUInt32LE(p+42),name=b.subarray(p+46,p+46+nl).toString("utf8"); if(name.toLowerCase().endsWith('.csv')){const lnl=b.readUInt16LE(lo+26),lel=b.readUInt16LE(lo+28),start=lo+30+lnl+lel,data=b.subarray(start,start+size); if(method===0)return data.toString('latin1'); if(method===8)return inflateRawSync(data).toString('latin1'); throw new Error('Método ZIP não suportado')} p+=46+nl+el+cl} throw new Error('CSV não encontrado no ZIP') }
function parseCsvLine(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===';'&&!q){out.push(cur);cur=''}else cur+=c}out.push(cur);return out}
function norm(s=''){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
export async function candidatesByOffice(cargo){const allowed=new Set(['1','3','5','6','7']);cargo=String(cargo||'6');if(!allowed.has(cargo))throw new Error('Cargo inválido');const data=await cached(`cand-${cargo}`,()=>fetchJson(`${TSE}/candidatura/listar/2026/${cargo==='1'?'BR':'MA'}/${ELECTION_ID}/${cargo}/candidatos`));const list=(data.candidatos||[]).map(c=>({id:c.id||c.idCandidato||c.sqCand,name:c.nomeUrna||c.nomeCompleto||c.nome,fullName:c.nomeCompleto||c.nome,number:String(c.numero||''),party:c.partido?.sigla||c.siglaPartido||'',partyName:c.partido?.nome||c.nomePartido||'',status:c.descricaoSituacao||c.situacao||c.descricaoTotalizacao||'',photo:c.urlFoto||c.fotoUrl||null,coalition:c.nomeColigacao||c.coligacao?.nome||''}));return {source:'TSE DivulgaCandContas',updatedAt:new Date().toISOString(),cargo:data.cargo||null,count:list.length,candidates:list}}
async function sectionData(){return cached('sections-ma',async()=>{const pkg=await fetchJson(CKAN),resources=pkg?.result?.resources||[],res=resources.find(x=>x.id==='76bf9d43-02ef-4d74-9507-482b7cb349ee')||resources.find(x=>/MA.*se[cç][aã]o/i.test(`${x.name} ${x.description||''}`));if(!res?.url)throw new Error('Recurso MA por seção não localizado');const r=await fetch(res.url,{headers:{'User-Agent':'Civica-MA/2.0'}});if(!r.ok)throw new Error(`Download de seções respondeu ${r.status}`);const text=extractFirstCsv(await r.arrayBuffer()),lines=text.split(/\r?\n/).filter(Boolean),hdr=parseCsvLine(lines[0]),idx=Object.fromEntries(hdr.map((h,i)=>[h.replace(/^\uFEFF/,''),i])),keys={mun:idx.NM_MUNICIPIO,zona:idx.NR_ZONA,secao:idx.NR_SECAO,eleitores:idx.QT_ELEITORES_PERFIL};if(Object.values(keys).some(v=>v===undefined))throw new Error('Layout do arquivo de seções mudou');const map=new Map();for(let i=1;i<lines.length;i++){const row=parseCsvLine(lines[i]),mun=row[keys.mun],zona=row[keys.zona],secao=row[keys.secao];if(!mun||!zona||!secao)continue;const k=`${mun}|${zona}|${secao}`,prev=map.get(k)||{municipio:mun,zona:Number(zona),secao:Number(secao),eleitores:0};prev.eleitores+=Number(row[keys.eleitores]||0);map.set(k,prev)}return [...map.values()]})}
export async function sectionsByMunicipality(municipio=''){const all=await sectionData(),q=norm(municipio),filtered=q?all.filter(x=>norm(x.municipio)===q):all,zones=[...new Set(filtered.map(x=>x.zona))].sort((a,b)=>a-b),eleitores=filtered.reduce((s,x)=>s+x.eleitores,0);return {source:'TSE Dados Abertos — Perfil do eleitorado por seção 2026 MA',updatedAt:new Date().toISOString(),municipio:municipio||null,count:filtered.length,zones,eleitores,sections:filtered}}
